project:
  type: website
  output-dir: docs
  resources:
    - "cv_osamura_27092026.pdf"
    - "fonts/"

website:
  title: "Koichi Osamura"
  description: "Koichi Osamura, political scientist at the University of Vienna, working on coalition politics, legislative behavior and party competition."
  sidebar: false
  search: false
  page-navigation: false
  navbar:
    logo: ""
    favicon: ""
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - media.qmd
      - teaching.qmd
      - cv.qmd
    right:
      - text: "{{< iconify fa6-brands:linkedin >}}"
        aria-label: Linkedin
        href: https://www.linkedin.com/in/koichiosamura
        target: _blank
      #- icon: twitter
      #  href: https://twitter.com/koichiosamura
      - text: "{{< iconify fa6-brands:bluesky >}}"
        aria-label: Bluesky
        href: https://bsky.app/profile/koichiosamura.bsky.social
        target: _blank
      - text: "{{< iconify fa6-brands:orcid >}}"
        aria-label: Orcid
        href: https://orcid.org/0000-0001-8907-9138
        target: _blank
      - icon: github
        href: https://github.com/koichiosamura
        target: _blank
      # - text: "{{< iconify fa7-solid:building-columns >}}"
      #   aria-label: University of Vienna
      #   href: https://ufind.univie.ac.at/en/person.html?id=1004088
    search: false
  page-footer:
    left: "© 2026 Koichi Osamura"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: [flatly, styles.scss]
    css: fonts/fonts.css
    toc: true
    toc-title: "On this page"

editor: source
