---
title: "Research"
---

### In progress

- **Dissertation**
  - **What is the price of loyalty? An analysis on the efficiency of presidential perks in sustaining legislative support in South America**
    - Supervised by Prof. Thomas M. Meyer, PhD, and Prof. Dr. Laurenz Ennser-Jedenastik.\
<br>
- **Projects beyond dissertation**
  - **The Politics of Portfolio Design in European Democracies**
    - PI: Thomas Meyer, PhD (University of Vienna) and Dr. Ulrich Sieberer (University of Bamberg).
    - Funding: Austrian Science Fund (grant number: I 5876-G) and German Research Foundation (grant number: SI 1470/9-1)
    - Collaborators: David Schmuck, Hanna Bäck, Andrea Ceron, Albert Falcó-Gimeno, Benjamin Giunaudeau, Isabelle Guinaudeau, Martin Ejnar Hansen, Kristoffer Kolltveit, Tom Louwerse, Wolfgang C. Müller, and Thomas Persson.
    - Website: [https://governmentportfolios.eu/](https://governmentportfolios.eu/)\
<br>
  - **Ideological synergies as proxy for coalition efficiency in presidential systems**
    - Presented at ECPR 2024 General Conference.\
<br>
  - **The weight of patronage on the passage of salient policies in presidential systems**
    - Presented at ECPR 2024 General Conference.
